export const PLANS = [
    {
        id: 'explorer',
        name: 'Explorer',
        price: 89,
        annualPrice: 890,
        priceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_EXPLORER || process.env.NEXT_PUBLIC_STRIPE_PRICE_EXPLORER || 'price_1RsodvP3GWiMooGSMQpJ0KL8',
        annualPriceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_EXPLORER_ANNUAL || process.env.NEXT_PUBLIC_STRIPE_PRICE_EXPLORER_ANNUAL || 'price_1Sn4siP3GWiMooGSc336SbzN',
        color: '#3b82f6',
        features: [
            'Límites más amplios de uso',
            'Crea múltiples perfiles',
            'Análisis profundo de patrones',
            'REMI recuerda tu historia completa',
        ],
    },
    {
        id: 'warrior',
        name: 'Warrior',
        price: 299,
        annualPrice: 2990,
        priceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_WARRIOR || process.env.NEXT_PUBLIC_STRIPE_PRICE_WARRIOR || 'price_1RqOMRP3GWiMooGSD5OPjzim',
        annualPriceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_WARRIOR_ANNUAL || process.env.NEXT_PUBLIC_STRIPE_PRICE_WARRIOR_ANNUAL || 'price_1Sn4uNP3GWiMooGSsVmPQzAg',
        color: '#f97316',
        popular: true,
        features: [
            'REMI LIVE: sesiones ilimitadas de voz',
            'Uso extendido sin interrupciones',
            'Respuestas más largas y detalladas',
            'Decodificador de mensajes incluido',
        ],
    },
    {
        id: 'phoenix',
        name: 'Phoenix',
        price: 449,
        annualPrice: 4490,
        priceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_PHOENIX || process.env.NEXT_PUBLIC_STRIPE_PRICE_PHOENIX || 'price_1RqOM5P3GWiMooGS8k3BDdW8',
        annualPriceId: process.env.EXPO_PUBLIC_STRIPE_PRICE_PHOENIX_ANNUAL || process.env.NEXT_PUBLIC_STRIPE_PRICE_PHOENIX_ANNUAL || 'price_1Sn4uhP3GWiMooGSwqepVrYh',
        color: '#ec4899',
        badge: 'MEJOR VALOR',
        features: [
            'REMI LIVE: voz con IA sin límites',
            'Uso ilimitado',
            'Acceso total sin restricciones',
            'Más perfiles',
        ],
    },
];
